workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

include: 'https://gitlab.com/nomadic-labs/gitlab-ocaml-ci-example/-/raw/main/.gitlab-ci.yml'

.build-matrix:
  parallel:
    matrix:
    - OCAML_COMPILER: ["4.14.1"]
      DUNE_BUILD_TARGETS: "@src/all"
      DUNE_TEST_TARGETS: "@runtest"
      DUNE_DOC_TARGETS: [""]
    - OCAML_COMPILER: "4.14.1"
      DUNE_BUILD_TARGETS: [""]
      DUNE_TEST_TARGETS: "@fmt"
      DUNE_DOC_TARGETS: "@doc"

variables:
  CLEAN_OPAM_CACHE: "false"
  CLEAN_DUNE_CACHE: "false"
